### ISSUE TITLE
patching / compiling kernel with Auvidea J20 CSI camera module support, missing files..

### ISSUE THREAD

**Issue by Spawn32** [jetsonhacks/buildJetsonTX2Kernel#11]
Hi,
I have patched the kernel source (jetpack 3.2) to include the Auvidea J20 module, selected and enabled it in xconfig.

But while compiling it looks for this files and cant find them:

+#include <media/v4l2-chip-ident.h>
+#include <media/camera_common.h>	
+#include <media/soc_camera.h>

drivers/media/i2c/j20.c:32:35: fatal error: media/v4l2-chip-ident.h: No such file or directory

I can manually locate and copy the camera_common.h and soc_camera.h, but those again wants a lot of other header files that are suppose to be in media/ 

The v4l2-chip-ident.h is no where to be found, but i am sure i am doing something wrong, i should-en need to locate this files should i ?	

I am compiling the kernel directly on the TX2 like this description:	
https://github.com/jetsonhacks/buildJetsonTX2Kernel

I have also downloaded the kernel sources on my Ubuntu machine just in case there was some difference between building on the TX2 or a Ubuntu pc, but the v4l2-chip-ident.h is still no where to be found, going crazy here :)

**Comment by jetsonhacks** [comment]
The sources downloaded by these scripts are for the Jetson carrier boards. The kernel sources for the Auvidea boards are likely different. I do not know if Auvidea have updated their kernel sources for L4T 28.2. You will have to contact Auvidea for the source.

**Comment by tidus747** [comment]
@Spawn32 @jetsonhacks There are any news about how to make work the Auvidea J20 on the Jetson TX2? Thanks
