### ISSUE TITLE
kernel source code for L4T28.1 

### ISSUE THREAD

**Issue by Mingczpala** [jetsonhacks/buildJetsonTX2Kernel#15]
The kernel source must match the version of L4T that has been flashed onto the Jetson. For example, here we use the kernel source for L4T 28.1 with L4T 28.1. Kernel versions are not compatible across releases.
----
I don't want to update my L4T, how can I download the kernel source for the version of L4T28.1??

**Comment by jetsonhacks** [comment]
Use the appropriate release:
$ git clone https://github.com/jetsonhacks/buildJetsonTX2Kernel.git
$ cd buildJetsonTX2Kernel
$ git checkout vL4T28.1
