### ISSUE TITLE
Readme mistake or script bug?

### ISSUE THREAD

**Issue by DrTon** [jetsonhacks/buildJetsonTX2Kernel#29]
Readme says about getKernelSources.sh:

>Downloads the kernel sources for L4T from the NVIDIA website, decompresses them and **opens a graphical editor on the .config file**.

But this doesn't happen for me (master, TX2, L4T 32.3.1). Is is expected behavior (then Readme should be fixed) or bug?

In scripts/getKernelSources.sh I see that it calls scripts/config but graphical tool doesn't appear.

**Comment by jetsonhacks** [comment]
Thank you for catching this. It is a README issue. The script was modified to remove the requirement of the GUI, which many deemed too heavy for the task. editConfig.sh opens the editor.
