### ISSUE TITLE
how to compile device tree blobs?

### ISSUE THREAD

**Issue by TonyMou** [jetsonhacks/buildJetsonTX2Kernel#3]
Hi, jetsonhacks!
I find that the makeKernel.sh would not make dtbs.
If we want to compile device tree and update it, 

would adding "make dtbs" in the makeKernel.sh and "sudo cp /arch/arm64/boot/dts/xxxxx.dtb /boot/" in copyKernel.sh files work this out?

**Comment by jetsonhacks** [comment]
The compiled device tree files are stored on a separate partition on the Jetson eMMC, therefore the method you suggest does not work.

**Comment by vaibhavviswanathan** [comment]
You mention that we need to compile the device tree separately. How do we do this?

**Comment by JetsonHacksNano** [comment]
The easiest way is to follow the NVIDIA directions to use a device tree compiler and flash the device tree from a host PC.
