### ISSUE TITLE
updating device tree

### ISSUE THREAD

**Issue by shomahi** [jetsonhacks/buildJetsonTX2Kernel#34]
Hello,

Does these scripts update device tree files? how can I add a device to the device tree of jetson?

Thanks,

**Comment by jetsonhacks** [comment]
These scripts do not deal with the device tree. To modify the device tree, please refer to the official NVIDIA docs, or ask a specific question on the official NVIDIA Jetson forums, where a large group of developers and NVIDIA engineers share their experience: https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70
