### ISSUE TITLE
IMX274 Camera with kernel build

### ISSUE THREAD

**Issue by zwagner88** [jetsonhacks/buildJetsonTX2Kernel#5]
I am trying to build the kernel to activate CP210x USB converter drivers, and have already installed a custom kernel build for Leopard Images IMX274 cameras.  After building the kernel with these scripts, the Cameras no longer work.  I am new to kernel building, so I don't really understand what is going wrong, that's why I really like your scripts, here.  I have attached the instructions that came with the cameras.  Is there a way to bring in the settings that I currently have set when building the kernel, or is there something else that I can do to make this work?

[IMX274_R28.1_TX2_NV_20171027.txt](https://github.com/jetsonhacks/buildJetsonTX2Kernel/files/1615658/IMX274_R28.1_TX2_NV_20171027.txt)

**Comment by jetsonhacks** [comment]
There are a lot of changes that are made to get their kernel to work. Unfortunately there are too many issues to easily list what changes you need to make if you are not familiar with building kernels. The source code must match your modified kernel, and the local version of your kernel should match your compiled drivers. 

There are two options: Follow the Leopard instructions of building the kernel and modify it for the CP210x. The second option is to flash with the Leopard image, download the sources and so on, make sure that the local version matches the running kernel in the configuration step, add the CP210x driver, and then compile only the modules. Once that is complete, copy only the CP210x driver to the correct file directory. Good luck!
