### ISSUE TITLE
if we want to include iwlwifi driver and build this module

### ISSUE THREAD

**Issue by wcyu1205** [jetsonhacks/buildJetsonTX2Kernel#6]
Hi Sir,
If we want to include iwlwifi driver, and build install this module,
how to do that?

**Comment by jetsonhacks** [comment]
This is not an issue with the scripts here. You may ask general purpose questions in the official NVIDIA Jetson TX2 forum: https://devtalk.nvidia.com/default/board/188/jetson-tx2/

**Comment by wcyu1205** [comment]
So the kernel you provided cannot build iwlwifi module?

**Comment by jetsonhacks** [comment]
These are scripts to build a kernel, the kernel settings are your choice.
